/*
 * WARNING: do not edit!
 * Generated by util/mkbuildinf.pl
 *
 * Copyright 2014-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#define PLATFORM "platform: android-x86_64"
#define DATE "built on: Sun Aug 10 00:00:14 2025 UTC"

/*
 * Generate compiler_flags as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char compiler_flags[] = {
    'c','o','m','p','i','l','e','r',':',' ','x','8','6','_','6','4',
    '-','l','i','n','u','x','-','a','n','d','r','o','i','d','2','1',
    '-','c','l','a','n','g',' ','-','f','P','I','C',' ','-','p','t',
    'h','r','e','a','d',' ','-','W','a',',','-','-','n','o','e','x',
    'e','c','s','t','a','c','k',' ','-','Q','u','n','u','s','e','d',
    '-','a','r','g','u','m','e','n','t','s',' ','-','W','a','l','l',
    ' ','-','O','3',' ','-','D','O','P','E','N','S','S','L','_','U',
    'S','E','_','N','O','D','E','L','E','T','E',' ','-','D','O','P',
    'E','N','S','S','L','_','P','I','C',' ','-','D','O','P','E','N',
    'S','S','L','_','B','U','I','L','D','I','N','G','_','O','P','E',
    'N','S','S','L',' ','-','D','N','D','E','B','U','G',' ','-','D',
    '_','_','A','N','D','R','O','I','D','_','A','P','I','_','_','=',
    '2','1','\0'
};
